import CrewGrid from '@/components/CrewGrid';
import Head from "next/head";
import styles from '../../styles/Crew.module.css';

export default function Destination() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main id="main">
                <CrewGrid />
            </main>

            <div className={styles.pageBg}>

            </div>
        </>
    );
}